### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-christopheremv#2]
[reporte calculadora dll.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-christopheremv/files/6330071/reporte.calculadora.dll.pdf)

**Comment by Band-hi** [comment]
Practica 97/100
Calificación 19.4/20

-Adjuntar títulos de imágenes
-Faltan líneas en la conclusión.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
